spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # craete-drop의 의미는 SessionFactory가 시작될 때 Drop, Create, Alter를 하고 종료될 때 Drop을 진행함.
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    me.silvernine: DEBUG

jwt:
  header: Authorization
  # HS512 알고리즘을 사용하기 때문 Secret Key는 64Byte 이상
  # 해당 값은 Secret Key를 Base64로 인코딩한 값을 사용
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰의 만료시간 24시간
  token-validity-in-seconds: 86400
